api_server_port: 8081
mcp_server_url: http://localhost:8080/events
mcp_server_port: 8080
tools_enabled:
  - get_weather

tracing:
  enabled: false
  service_name: mcp-kit
  endpoint_address: localhost:4317
  timeout: 5s
  sampling_rate: 1.0
  batch_timeout: 5s
  environment: development
  version: 0.1.0

auth:
  domain: "${AUTH_DOMAIN}"
  client_id: "${AUTH_CLIENT_ID}"
  client_secret: "${AUTH_CLIENT_SECRET}"
  callback_url: "${AUTH_CALLBACK_URL}"
  token_ttl: 1h
  audience: ""

google:
  client_id: "${GOOGLE_CLIENT_ID}"
  client_secret: "${GOOGLE_CLIENT_SECRET}"
  redirect_url: "${GOOGLE_REDIRECT_URL}"
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
    - "https://www.googleapis.com/auth/userinfo.profile"
  state_cookie: "static-value-for-now"
  token_source_file: "/tmp/google_auth_token_source.json"
  enabled: false

tools:
  get_wether:
    enabled: true
  postgres:
    enabled: true
    databases:
      - name: "mcp_kit"
        host: "localhost"
        username: "root"
        password: "root"
        port: 5432
        sslmode: "disable"
  github_repository:
    enabled: true
    token: "${GITHUB_TOKEN}"
  github_issues:
    enabled: true
    token: "${GITHUB_TOKEN}"
  github_pull_requests:
    enabled: true
    token: "${GITHUB_TOKEN}"
  github_search:
    enabled: true
    token: "${GITHUB_TOKEN}"
  filesystem:
    enabled: true
    allowed_directory: "/tmp"
    blocked_pattern:
      - "secret"
      - "password"
  git:
    enabled: true
    default_repo_path: "/tmp"
    blocked_commands:
      - "push"
      - "pull"
      - "fetch"
  curl:
    enabled: true
    blocked_methods:
      - "POST"
      - "PUT"
      - "DELETE"
  bash:
    enabled: true
  sed:
    enabled: true
  grep:
    enabled: true
  gmail:
    enabled: true
    token: "${GMAIL_TOKEN}"