api_server_port: 8081
mcp_server_url: http://localhost:8080/events
mcp_server_port: 8080
tools_enabled:
  - get_weather

tracing:
  enabled: false
  service_name: mcp-kit
  endpoint_address: localhost:4317
  timeout: 5s
  sampling_rate: 1.0
  batch_timeout: 5s
  environment: development
  version: 0.1.0

auth:
  domain: "${AUTH_DOMAIN}"
  client_id: "${AUTH_CLIENT_ID}"
  client_secret: "${AUTH_CLIENT_SECRET}"
  callback_url: "${AUTH_CALLBACK_URL}"
  token_ttl: 1h
  audience: ""

google:
  client_id: "${GOOGLE_CLIENT_ID}"
  client_secret: "${GOOGLE_CLIENT_SECRET}"
  redirect_url: "${GOOGLE_REDIRECT_URL}"
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
    - "https://www.googleapis.com/auth/userinfo.profile"
  state_cookie: "static-value-for-now"
  token_source_file: "/home/shaharia/Projects/mcp-kit/token.json"
  enabled: false