version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "8080:8080"
    environment:
      - MCP_SERVER_PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: server
    networks:
      - mcp-network

  mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-client
    ports:
      - "8081:8081"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MCP_SERVER_URL=http://mcp-server:8080/events
    command: api
    depends_on:
      - mcp-server
    networks:
      - mcp-network

networks:
  mcp-network:
    name: mcp-network
    driver: bridge

volumes:
  postgres_data: