version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mcp-network:
    name: mcp-network
    driver: bridge

volumes:
  postgres_data: