server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            log: log
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: '(?P<log_level>(DEBUG|INFO|WARNING|ERROR)).*?(\[method=(?P<method>[^\s\]]+))?\s*(path=(?P<path>[^\s\]]+))?\s*(query=(?P<query>[^\]]*)\])?'
      - labels:
          log_level:
          method:
          path: