name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'mcp-frontend/package-lock.json'

      - name: Install Frontend Dependencies
        run: cd mcp-frontend && npm ci

      - name: Build Frontend
        run: cd mcp-frontend && npm run build

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: cmd/static
          retention-days: 1

  unit-test:
    name: Backend Unit Tests
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Download Frontend Build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: cmd/static

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run Backend Tests
        run: make test

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-pr${{ github.event.pull_request.number }}-${{ github.sha }}
          path: coverage.out
          retention-days: 1

  lint:
    name: Linting
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
          check-latest: true
          cache: true
          go-version-file: 'go.mod'
          cache-dependency-path: |
            go.sum

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-analysis:
    runs-on: ubuntu-latest
    needs: [ unit-test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download backend test coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-pr${{ github.event.pull_request.number }}-${{ github.sha }}
          path: ./
        continue-on-error: true

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    name: Docker Build
    needs:
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: false
          load: true
          tags: mcp:${{ github.event.pull_request.number }}-${{ github.sha }}

      - name: Cleanup
        if: always()
        run: docker image rm mcp:${{ github.event.pull_request.number }}-${{ github.sha }}

  release:
    name: Test Release
    needs:
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.23'

      - name: Download Frontend Build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: cmd/static

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create temporary tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a v${{ github.run_number }}.0.0 -m "Test tag for GoReleaser"

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --skip=publish --clean --fail-fast --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}